version: '3'
services:
  nexus:
    container_name: nexus
    image: klo2k/nexus3
    ports:
      - 7081:8081
    volumes:
      - nexus-data:/nexus-data
    restart: always
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    memswap_limit: 4g
    networks:
      - nginxproxymanager_default

volumes:
  nexus-data:

networks:
  nginxproxymanager_default:
    name: nginxproxymanager_default
    external: true
