version: '3.8'
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "root"
      DB_MYSQL_PASSWORD: "Jam*8mariadbsintov"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./nginx-proxy-manager:/data
      - ./letsencrypt:/etc/letsencrypt
