version: '2'

services:
  docker-registry:
    container_name: docker-registry
    image: registry:latest
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./registry/storage:/var/lib/registry
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
    
  docker-registry-ui:
    container_name: docker-registry-ui
    image: joxit/docker-registry-ui:1.5-static
    restart: always
    ports:
      - 8080:80
    environment:
      - REGISTRY_URL=http://docker-registry:5000
      - DELETE_IMAGES=true
