version: '3.9'

volumes:
  passbolt-db:
  passbolt-data-gpg:
  passbolt-data-jwt:

services:
  passbolt-db:
    container_name: passbolt-db
    image: mariadb:10.3
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=$PASSBOLT_DB_NAME
      - MYSQL_USER=$PASSBOLT_DB_USER
      - MYSQL_PASSWORD=$PASSBOLT_DB_PASS
    volumes:
      - passbolt-db:/var/lib/mysql

  passbolt:
    container_name: passbolt-app
    image: anatomicjc/passbolt:latest-ce-multiarch
    restart: unless-stopped
    depends_on:
      - passbolt-db
    environment:
      - APP_FULL_BASE_URL=https://pb.pangsoramdepo.com
      - DATASOURCES_DEFAULT_HOST=passbolt-db
      - DATASOURCES_DEFAULT_USERNAME=$PASSBOLT_DB_USER
      - DATASOURCES_DEFAULT_PASSWORD=$PASSBOLT_DB_PASS
      - DATASOURCES_DEFAULT_DATABASE=$PASSBOLT_DB_NAME
      - EMAIL_TRANSPORT_DEFAULT_HOST=smtp.gmail.com
      - EMAIL_TRANSPORT_DEFAULT_PORT=587
      - EMAIL_TRANSPORT_DEFAULT_USERNAME=$EMAIL_TRANSPORT_DEFAULT_USERNAME
      - EMAIL_TRANSPORT_DEFAULT_PASSWORD=$EMAIL_TRANSPORT_DEFAULT_PASSWORD
      - EMAIL_TRANSPORT_DEFAULT_TLS=true
      - EMAIL_DEFAULT_FROM=pangsoramdepo@gmail.com
    volumes:
      - passbolt-data-gpg:/etc/passbolt/gpg
      - passbolt-data-jwt:/etc/passbolt/jwt
