version: '3'
services:

  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.6
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: debezium/kafka:1.6
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  debezium:
    container_name: debezium
    image: debezium/connect:1.6
    ports:
      - 8083:8083
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    volumes:
      - ./config:/kafka/config

  debezium-ui:
    container_name: debezium-ui
    image: debezium/debezium-ui:2.1.2.Final
    ports:
      - 9080:8080
    environment:
      - KAFKA_CONNECT_URIS=http://debezium:8083
    depends_on:
      - debezium
  
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - debezium
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPERCONNECT=zookeeper:2181
      - KAFKA_CLUSTERS_0_SCHEMA_REGISTRY_URL=http://schemaregistry:8085
      - KAFKA_CLUSTERS_0_OFFSETSTORAGE_TOPIC=my_connect_offsets
      - KAFKA_CLUSTERS_0_CONFIGSTORAGE_TOPIC=my_connect_configs
      - KAFKA_CLUSTERS_0_STATUSSTORAGE_TOPIC=my_connect_statuses
      - DYNAMIC_CONFIG_ENABLED=true

  schemaregistry:
    container_name: schemaregistry
    image: confluentinc/cp-schema-registry:7.6.1
    restart: always
    depends_on:
      - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: "PLAINTEXT"
    ports:
    - 8085:8085
