server.host: "0.0.0.0"
# server.shutdownTimeout: "5s"
# server.publicBaseUrl: https://kibana.pangsoramdepo.com
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true